/**CREATE THE TABLE **/

CREATE TABLE AUG26UNIVERSITY(
UNIVERSITYCODE INT,
UNIVERSITYNAME VARCHAR(256),
UNIVERSITYADDRESS VARCHAR(256),
UNIVERSITY_NUMBER INT,
UNIVERSITY_LOCATION VARCHAR,
UNIVERSITY_PHONE INTEGER,
UNIVERSITY_DATE DATE,
UNIVERSITY_STATUS BOOLEAN,
UNIVERSITY_ALTERNATE_PHONE NUMERIC,
UNIVERSITY_TIME TIME,
UNIVERSITY_UUID UUID DEFAULT gen_random_uuid(),
UNIVERSITY_LOOKUP VARCHAR(256),
PRIMARY KEY (UNIVERSITYCODE)
);

CREATE TABLE AUG09(
UNIVERSITYID INT,
UNIVERSIRTY_NAME VARCHAR(256),
UNIVERSITY_NUMBER NUMERIC
);

CREATE TABLE STUDENT (
    STUDENTID INT PRIMARY KEY,
    STUDENTNAME VARCHAR(100),
    STUDENTAGE INT,
    UNIVERSITYCODE INT,
    FOREIGN KEY (UNIVERSITYCODE) REFERENCES UNIVERSITY(UNIVERSITYCODE)
);
/**
Add new column
rename the existing column
drop the column
delete the table
delete the rows(records)
**/
ALTER TABLE AUG26UNIVERSITY ADD COLUMN UNVERSITY_EMAIL VARCHAR(256);
ALTER TABLE AUG26UNIVERSITY ADD COLUMN UNIVESITY_CEO VARCHAR(256);
ALTER TABLE AUG26UNIVERSITY RENAME COLUMN UNIVESITY_CEO TO UNIVERSITY_CEO;
ALTER TABLE AUG26UNIVERSITY DROP COLUMN UNIVERSITY_CEO;
DROP TABLE IF EXISTS AUG09;
TRUNCATE TABLE AUG09;
SELECT * FROM AUG09;

/**
adding constraints(rule) to the table for specific column
priamry constraints
foreign key constraints

**/

ALTER TABLE AUG09 ADD CONSTRAINT pk_universityid PRIMARY KEY (UNIVERSITYID);
ALTER TABLE users ALTER COLUMN age TYPE VARCHAR(3);


/*SELECT */

SELECT * FROM AUG26UNIVERSITY;
SELECT * FROM AUG26STUDENT;
SELECT UNIVERSITYNAME FROM AUG26UNIVERSITY;
SELECT * FROM AUG26UNIVERSITY WHERE UNIVERSITYCODE = 1;
SELECT column_name, data_type 
FROM INFORMATION_SCHEMA.COLUMNS
WHERE UPPER(TABLE_NAME) = 'AUG26UNIVERSITY';


/*UPDATE*/

UPDATE AUG26UNIVERSITY SET UNIVERSITYADDRESS = 'MAD' WHERE UNIVERSITYCODE = '5';
UPDATE AUG26UNIVERSITY SET UNIVERSITYADDRESS = 'MADRAS',UNIVERSITY_NUMBER = 2000 WHERE UNIVERSITYCODE = '4';

UPDATE aug26university
SET
    universityaddress =
        CASE
            WHEN universitycode = '6' THEN
                'MADURAI'
            WHEN universitycode = '8' THEN
                'TTHANJAVUR'
        END
WHERE
    universitycode IN (
        '6',
        '8'
    );
    
/*INSERT*/

INSERT INTO AUG26STUDENT (STUDENT_ID) VALUES (1);


/*Delete*/

DELETE FROM AUG26UNIVERSITY WHERE UNIVERSITYCODE = '7';


